//Write a function called RepeatAlpha that takes a string and displays it repeating each alphabetical character as many times as its alphabetical index.
//'a' becomes 'a', 'b' becomes 'bb', 'e' becomes 'eeeee', etc...
